# Generated by Django 3.1 on 2020-08-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wymarzony_pies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('open_form', models.IntegerField()),
                ('open_to', models.IntegerField()),
                ('training', models.ManyToManyField(to='wymarzony_pies.Training')),
            ],
        ),
        migrations.RemoveField(
            model_name='customer',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='localization',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default=0, max_length=256, verbose_name='Twój adres'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default=0, max_length=128, verbose_name='Imię Klienta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='pet_name',
            field=models.CharField(max_length=128, verbose_name='Imię psa'),
        ),
        migrations.DeleteModel(
            name='Localization',
        ),
        migrations.AddField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='wymarzony_pies.location'),
            preserve_default=False,
        ),
    ]
