# Generated by Django 3.1 on 2020-08-12 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wymarzony_pies', '0002_auto_20200812_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.IntegerField(null=True),
        ),
    ]
