# Generated by Django 3.1 on 2020-08-19 13:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wymarzony_pies', '0005_auto_20200819_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateField(default=datetime.date.today, verbose_name='Data szkolenia'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wymarzony_pies.location', verbose_name='Wybierz szkołę'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_from',
            field=models.IntegerField(verbose_name='Rezerwacja od'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='res_to',
            field=models.IntegerField(verbose_name='Rezerwacja do'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wymarzony_pies.trainer', verbose_name='Twój trener'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wymarzony_pies.training', verbose_name='Rodzaj szkolenia'),
        ),
    ]
